module(
    name = "gaia_net",
    version = "0.3.0.dev2025729",
    compatibility_level = 1,
)
bazel_dep(name = "rules_proto", version = "6.0.0.bcr.1", repo_name = "rules_proto")
bazel_dep(name = "apple_support", version = "1.17.1", repo_name = "build_bazel_apple_support")
bazel_dep(name = "rules_apple", version = "3.16.0", repo_name = "build_bazel_rules_apple")
bazel_dep(name = "googleapis", version = "0.0.0-20240819-fe8ba054a", repo_name = "com_google_googleapis")
bazel_dep(name = "protobuf", version = "27.3", repo_name = "com_google_protobuf")
non_module_dependencies = use_extension("//bazel:defs.bzl", "non_module_dependencies")
use_repo(
    non_module_dependencies,
    "rules_foreign_cc",
    "rules_python",
    "rules_cc",
    "platforms",
    "upb",
    "com_google_absl",
    "com_github_openssl_openssl",
    "com_github_grpc_grpc",
    "com_github_nlohmann_json",
    "com_google_googletest",
    "com_github_gflags_gflags",
    "com_github_fmtlib_fmt",
    "com_github_lz4",
    "com_github_hiredis",
    "com_github_redis_plus_plus",
)



